name: Android CI

on:
  push:
    branches: [ 'master', 'ci' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:
    inputs:
      lsl_ref:
        description: 'liblsl tag / branch to build'
        required: false
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'liblsl-Java'
    - uses: actions/checkout@v3
      with:
        repository: sccn/liblsl
        path: 'liblsl'
        ref: ${{ github.event.inputs.lsl_ref }}
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: 'cd liblsl-Java && cmake --version && ./gradlew assembleRelease'
    - name: upload install dir
      uses: actions/upload-artifact@master
      with:
        name: AAR
        path: 'liblsl-Java/build/outputs/aar/*.aar'


